ALTER TYPE "TipoAcaoAudit" ADD VALUE IF NOT EXISTS 'AULA_CRIADA';
ALTER TYPE "TipoAcaoAudit" ADD VALUE IF NOT EXISTS 'AULA_ATUALIZADA';
ALTER TYPE "TipoAcaoAudit" ADD VALUE IF NOT EXISTS 'AULA_CANCELADA';
