DROP TABLE "SplitLojaAsaas";
DROP TABLE "CobrancaLojaAsaas";
DROP TABLE "PedidoLoja";
DROP TABLE "ContaAsaasLoja";

DROP TYPE "StatusPedidoLoja";
DROP TYPE "StatusContaAsaasLoja";

ALTER TYPE "Papel" RENAME TO "Papel_com_loja";

CREATE TYPE "Papel" AS ENUM (
  'GESTOR',
  'PROFESSOR',
  'ALUNO',
  'SECRETARIA'
);

ALTER TABLE "Usuario"
  ALTER COLUMN "papel" TYPE "Papel"
  USING ("papel"::text::"Papel");

DROP TYPE "Papel_com_loja";

ALTER TYPE "TipoAcaoAudit" RENAME TO "TipoAcaoAudit_com_loja";

CREATE TYPE "TipoAcaoAudit" AS ENUM (
  'CHECKIN_CRIADO',
  'CHECKIN_INVALIDADO',
  'CHECKIN_EXCLUIDO',
  'REGISTRO_RETROATIVO',
  'AJUSTE_HORAS',
  'ESTORNO_HORAS',
  'GRADUACAO',
  'PAGAMENTO',
  'PLANO',
  'TIPO_ALUNO',
  'STATUS_ALUNO',
  'IMPORTACAO',
  'CONCILIACAO_MANUAL',
  'COMPARECIMENTO_CANCELADO',
  'CONFIGURACAO',
  'AULA_CRIADA',
  'AULA_ATUALIZADA',
  'AULA_CANCELADA',
  'COMPARECIMENTO_NO_SHOW',
  'COMPARECIMENTO_PROMOVIDO_LISTA_ESPERA',
  'GESTOR_CRIADO',
  'OBSERVACAO_TECNICA',
  'ALUNO_CRIADO',
  'PROFESSOR_CRIADO',
  'MODALIDADE_CRIADA',
  'TURMA_CRIADA',
  'DOCUMENTO_ALUNO_ADICIONADO',
  'PROFESSOR_STATUS_ATUALIZADO',
  'MODALIDADE_CONFIGURADA',
  'TURMA_ATUALIZADA',
  'CHECKIN_BLOQUEADO_INADIMPLENCIA',
  'SECRETARIA_CRIADA',
  'TERMO_RESPONSABILIDADE_ACEITO',
  'MATRICULA_SOLICITADA',
  'MATRICULA_APROVADA',
  'MATRICULA_REJEITADA',
  'CONTA_ASAAS_PROFESSOR_SOLICITADA',
  'CONTA_ASAAS_PROFESSOR_DADOS_ATUALIZADOS'
);

ALTER TABLE "LogAuditoria"
  ALTER COLUMN "acao" TYPE "TipoAcaoAudit"
  USING ("acao"::text::"TipoAcaoAudit");

DROP TYPE "TipoAcaoAudit_com_loja";
