ALTER TYPE "TipoAcaoAudit" ADD VALUE 'ALUNO_CRIADO';
ALTER TYPE "TipoAcaoAudit" ADD VALUE 'PROFESSOR_CRIADO';
ALTER TYPE "TipoAcaoAudit" ADD VALUE 'MODALIDADE_CRIADA';
ALTER TYPE "TipoAcaoAudit" ADD VALUE 'TURMA_CRIADA';
