ALTER TYPE "Papel" ADD VALUE 'LOJA';
ALTER TYPE "TipoAcaoAudit" ADD VALUE 'LOJA_CRIADA';
ALTER TYPE "TipoAcaoAudit" ADD VALUE 'CONTA_ASAAS_LOJA_SOLICITADA';
ALTER TYPE "TipoAcaoAudit" ADD VALUE 'VENDA_LOJA';

CREATE TYPE "StatusContaAsaasLoja" AS ENUM (
  'CRIANDO',
  'RESULTADO_INDETERMINADO',
  'AGUARDANDO_ATIVACAO',
  'AGUARDANDO_APROVACAO',
  'HABILITADA',
  'BLOQUEADA',
  'ERRO',
  'DESABILITADA'
);

CREATE TYPE "StatusPedidoLoja" AS ENUM (
  'RASCUNHO',
  'AGUARDANDO_PAGAMENTO',
  'PAGO',
  'CANCELADO',
  'ESTORNADO',
  'CONCILIACAO'
);
