ALTER TYPE "StatusContaAsaasProfessor" ADD VALUE IF NOT EXISTS 'RASCUNHO' BEFORE 'CRIANDO';

ALTER TYPE "TipoAcaoAudit"
  ADD VALUE IF NOT EXISTS 'CONTA_ASAAS_PROFESSOR_DADOS_ATUALIZADOS';

ALTER TABLE "ContaAsaasProfessor"
  ALTER COLUMN "consentimentoVersao" DROP NOT NULL,
  ALTER COLUMN "consentidoEm" DROP NOT NULL;
